#!/usr/bin/env zsh

() {
	local root_dir="$(git rev-parse --show-toplevel)"
	local selene_config="${root_dir}/selene.toml"
	local stylua_config="${root_dir}/.stylua.toml"

	local file
	for file in $(git diff --name-only --staged --diff-filter=ACM); do
		case "${file##*.}" in
			lua)
				selene --config "$selene_config" "$file" || exit 1
				stylua --check --config-path="$stylua_config" "$file" || exit 1
				;;
			py)
				black --check "$file" || exit 1
				mypy --check --strict "$file" || exit 1
				;;
			bash | zsh | .zshrc | .zshenv)
				beautysh --check --tab "$file" || exit 1
				;;
			fish)
				fish --no-execute "$file" || exit 1
				fish_indent --check "$file" || exit 1
				;;
			nix)
				deadnix "$file" || exit 1
				statix check "$file" || exit 1
				nixfmt --check "$file" || exit 1

				nix flake check "$root_dir"
				;;
			yaml)
				yamllint "$file" || exit 1
				;;
			*)
				echo "🤷 Unknown file type ($file) 🤷\n"
				;;
		esac
	done

	gitleaks git --verbose
}
