#!/usr/bin/env zsh

() {
	local root_dir="$(git rev-parse --show-toplevel)"
	local selene_config="${root_dir}/selene.toml"
	local stylua_config="${root_dir}/.stylua.toml"

	local file
	for file in $(git diff --name-only --staged); do
		if [[ ! -f "$file" ]]; then
			continue
		fi

		case "${file##*.}" in
			lua)
				selene --config "$selene_config" "$file" || exit 1
				stylua --check --config-path="$stylua_config" "$file" || exit 1
				;;
			py)
				black --check "$file" || exit 1
				mypy --check --strict "$file" || exit 1
				;;
			zsh)
				beautysh --check --tab "$file" || exit 1
				;;
			fish)
				fish --no-execute "$file" || exit 1
				fish_indent --check "$file" || exit 1
				;;
			nix)
				deadnix "$file"
				statix check "$file"
				nixfmt --check "$file"

				darwin-rebuild check --flake "${root_dir}"
				;;
			*)
				echo "🤷 Unknown file type ($file) 🤷\n"
				;;
		esac
	done
}
