#!/usr/bin/env zsh

() {
	local root_dir="$(git rev-parse --show-toplevel)"
	local luacheck_config="${root_dir}/.luacheckrc"
	local stylua_config="${root_dir}/.stylua.toml"

	local file
	for file in $(git diff --name-only --staged); do
		[[ ! -f "$file" ]] && continue

		local file_ext="${file##*.}"
		if [[ "$file_ext" == "lua" ]]; then
			luacheck --config="$luacheck_config" "$file" || exit 1
			stylua --check --config-path="$stylua_config" "$file" || exit 1
		elif [[ "$file_ext" == "py" ]]; then
			black --check "$file" || exit 1
			mypy --check --strict "$file" || exit 1
		elif [[ "$file_ext" == "zsh" ]]; then
			beautysh --check --tab "$file" || exit 1
		elif [[ "$file_ext" == "fish" ]]; then
			fish --no-execute "$file" || exit 1
			fish_indent --check "$file" || exit 1
		fi
	done
}
