"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vicmd_symbol = "[<](bold green)"

[status]
symbol = "X"
success_symbol = "V"
not_executable_symbol = "NOEXEC"
not_found_symbol = "?"
sigint_symbol = "SIGINT"
signal_symbol = "SIG"
format = "[$status]($style) "
pipestatus = true
pipestatus_separator = "| "
pipestatus_format = "[$pipestatus]($style)"
disabled = false

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[aws]
symbol = "aws "

[c]
symbol = "C "
disabled = true

[cobol]
symbol = "cobol "
disabled = true

[conda]
symbol = "conda "
disabled = true

[crystal]
symbol = "cr "
disabled = true

[cmake]
symbol = "cmake "
disabled = true

[daml]
symbol = "daml "
disabled = true

[dart]
symbol = "dart "

[deno]
symbol = "deno "

[dotnet]
symbol = ".NET "
disabled = true

[directory]
read_only = " ro"
fish_style_pwd_dir_length = 1

[docker_context]
symbol = "docker "

[elixir]
symbol = "exs "
disabled = true

[elm]
symbol = "elm "
disabled = true

[git_branch]
symbol = "git "

[golang]
symbol = "go "

[hg_branch]
symbol = "hg "
disabled = true

[java]
symbol = "java "
disabled = true

[julia]
symbol = "jl "
disabled = true

[kotlin]
symbol = "kt "

[lua]
symbol = "lua "

[nodejs]
symbol = "nodejs "

[memory_usage]
symbol = "memory "

[nim]
symbol = "nim "
disabled = true

[nix_shell]
symbol = "nix "
disabled = true

[ocaml]
symbol = "ml "
disabled = true

[package]
symbol = "pkg "

[perl]
symbol = "pl "
disabled = true

[php]
symbol = "php "
disabled = true

[pulumi]
symbol = "pulumi "

[purescript]
symbol = "purs "
disabled = true

[python]
symbol = "py "

[raku]
symbol = "raku "
disabled = true

[ruby]
symbol = "rb "
disabled = true

[rust]
symbol = "rs "

[scala]
symbol = "scala "
disabled = true

[spack]
symbol = "spack "
disabled = true

[sudo]
symbol = "sudo "
disabled = false

[swift]
symbol = "swift "
disabled = true

[kubernetes]
symbol = "kube "
format = '\[[$symbol$context( \($namespace\))]($style)\] '
disabled = false

[gcloud]
symbol = "gcloud "

[username]
disabled = false
show_always = true

[time]
disabled = false
