"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"

[status]
disabled = false
symbol = "X"
success_symbol = "V"
not_executable_symbol = "NOEXEC"
not_found_symbol = "?"
sigint_symbol = "SIGINT"
signal_symbol = "SIG"
format = '\[⚡[$status]($style)\] '
pipestatus = true
pipestatus_separator = "| "
pipestatus_format = "[$pipestatus]($style)"

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[c]
disabled = true

[cobol]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[cmake]
disabled = true

[daml]
disabled = true

[dotnet]
disabled = true

[directory]
fish_style_pwd_dir_length = 1

[elixir]
disabled = true

[elm]
disabled = true

[hg_branch]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[ocaml]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[purescript]
disabled = true

[raku]
disabled = true

[ruby]
disabled = true

[scala]
disabled = true

[spack]
disabled = true

[sudo]
disabled = false

[swift]
disabled = true

[kubernetes]
disabled = false
symbol = "☸️  "
format = '\[[$symbol$context( \($namespace\))]($style)\] '

[username]
disabled = false
format = "🤓 [$user]($style) "
show_always = true

[cmd_duration]
disabled = false
format = "⏱️  [$duration]($style) "

[time]
disabled = false
format = '[$time]($style) '
