#!/usr/bin/env zsh

alias v='nvim'
alias vim='nvim'

alias tree='exa --tree'

gsync() {
	git fetch --all --prune
	git pull --all --rebase --autostash
}
alias gupa='git pull --rebase --autostash origin "$(git branch --show-current)"'
alias ggpf='git push --force origin "$(git branch --show-current)"'
alias gprom='git pull --rebase --autostash origin master'
alias grbim='git rebase --interactive master'

update-hosts() {
	local current_hosts="$(cat /etc/hosts)"
	local anti_malware_hosts="$(curl https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts)"
	local fakenews_gambling_hosts="$(curl https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts)"

	echo "${current_hosts} \n${anti_malware_hosts} \n${fakenews_gambling_hosts}" | sed 's/^\s+\|\s+$//g' | sed '/^\s*#\|^$/d' | sort --unique | sudo tee /etc/hosts
}

alias kx='kubectx'
alias kc='kubectx --current'
