local keymap = require('vimrc.utils.keymapping')

keymap.nnoremap('<F9>', ':FloatermPrev<CR>', { desc = 'Previous Floaterm instance' })
keymap.tnoremap('<F9>', [[<C-\><C-n>:FloatermPrev<CR>]], { desc = 'Previous Floaterm instance' })
keymap.nnoremap('<F10>', ':FloatermNext<CR>', { desc = 'Next Floaterm instance' })
keymap.tnoremap('<F10>', [[<C-\><C-n>:FloatermNext<CR>]], { desc = 'Next Floaterm instance' })
keymap.nnoremap('<F11>', ':FloatermNew<CR>', { desc = 'New Floaterm instance' })
keymap.tnoremap('<F11>', [[<C-\><C-n>:FloatermNew<CR>]], { desc = 'New Floaterm instance' })
keymap.nnoremap('<F12>', ':FloatermToggle<CR>', { desc = 'Toggle show Floaterm' })
keymap.tnoremap('<F12>', [[<C-\><C-n>:FloatermToggle<CR>]], { desc = 'Toggle show Floaterm' })
