[alias]
	exec = "!exec "
	root = "!git rev-parse --show-toplevel"
	whoami = "!git config user.name && git config user.email"
	wt = "!git worktree "
[core]
	autocrlf = input
[help]
	autocorrect = 50

[include]
	path = ~/.config/git/git-diff.toml
	path = ~/.config/git/commit-sign.toml
