[alias]
	sh = "!exec "
	root = "!git rev-parse --show-toplevel"
	iam = "!git config user.name && git config user.email"
	wt = "!git worktree "
	fh = "!git log --follow --all --patch -- \"$(fzf)\""
[core]
	autocrlf = input
[help]
	autocorrect = 50

[include]
	path = ~/.config/git/git-diff.toml
	path = ~/.config/git/commit-sign.toml
