#!/usr/bin/env zsh

() {
	command git rev-parse --git-dir &> /dev/null || return 1

	local ref
	for ref in refs/{heads,remotes/{origin,upstream}}/{main,trunk}; do
		if $(git show-ref --quiet --verify "$ref"); then
			echo "${ref:t}"
			return
		fi
	done
	echo "master"
}
