name: Lint neovim lua config

on:
  push:
    paths:
      - dotfiles/nvim/**
  pull_request:
    paths:
      - dotfiles/nvim/**
  workflow_dispatch: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Luacheck linter
        uses: lunarmodules/luacheck@v0
        with:
          args: dotfiles/nvim/
