---
name: Lint python

on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - "**/*.py"
  pull_request:
    paths:
      - "**/*.py"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |-
          pip install --upgrade pip
          pip install mypy
      - run: mypy --strict $(git ls-files '*.py')
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
