name: Lint neovim config

on:
  push:
    paths:
      - dotfiles/nvim/**
  pull_request:
    paths:
      - dotfiles/nvim/**

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: master
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_LUA: true
          LINTER_RULES_PATH: /dotfiles/nvim/
