name: Check nix flake

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  check:
    name: check
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix run nix-darwin -- build --flake .#tickle
      - run: nix run nix-darwin -- check --flake .#tickle
